name: Build APK and EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

  build-exe:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Upload Windows Bundle Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-EXE-App
          path: build/windows/runner/Release/
